accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update_profile_submit/', views.update_profile_submit, name='update_profile_submit'),
]

hoodie_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_pages.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_pages/urls.py
from django.urls import path
from . import views

app_name = 'main_pages'

urlpatterns = [
    path('', views.main_page, name="main_page"),
    path('base/', views.base, name="base"),
    path('collection/<str:collection_name>/', views.collection_view, name="collection_view"),
    path('search/', views.search, name='search'),
    path('card/<int:product_id>/', views.card, name='card'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('cart/clear', views.clear_cart, name='clear_cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('cart/buy/', views.buy_cart, name='buy_cart'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout2'),
    path('signup/', views.register_view, name='signup'),
    path('cart/delete/<int:product_id>/', views.delete_cart_item, name='delete_cart_item'),
]

main_pages/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    FIO = models.TextField(verbose_name='ФИО')
    address = models.TextField(verbose_name='Адрес')
    image = models.ImageField(verbose_name='Фото профиля', upload_to='profile_images/')

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Collection(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название коллекции')

    class Meta:
        verbose_name = 'Коллекция'
        verbose_name_plural = 'Коллекции'

    def __str__(self):
        return self.name or ''


class Color(models.Model):
    color_id = models.CharField(primary_key=True, max_length=36)
    color_name = models.CharField(max_length=50, verbose_name='Цвет')

    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'

    def __str__(self):
        return self.color_name or ''


class DeliveryService(models.Model):
    delivery_service_id = models.CharField(primary_key=True, max_length=36)
    delivery_service_name = models.CharField(max_length=100, verbose_name='Служба доставки')

    class Meta:
        verbose_name = 'Служба доставки'
        verbose_name_plural = 'Службы доставки'

    def __str__(self):
        return self.delivery_service_name or ''


class Vendor(models.Model):
    vendor_name = models.CharField(primary_key=True, max_length=100, verbose_name='Поставщик')
    address = models.CharField(max_length=100, verbose_name='Адрес')

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'

    def __str__(self):
        return self.vendor_name or ''


class Material(models.Model):
    material_id = models.CharField(primary_key=True, max_length=36)
    material_name = models.CharField(max_length=50, verbose_name='Название материала')

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

    def __str__(self):
        return self.material_name or ''


class Product(models.Model):
    product_id = models.CharField(primary_key=True, max_length=36)
    product_name = models.CharField(max_length=100, verbose_name='Название товара', db_index=True)
    product_image = models.ImageField(verbose_name='Изображение товара', upload_to='product_images/')
    product_color = models.ForeignKey(Color, on_delete=models.CASCADE, verbose_name='Цвет', related_name='products')
    product_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    product_material = models.ForeignKey(Material, on_delete=models.CASCADE, verbose_name='Материал')
    description = models.TextField(default='Худи', verbose_name='Описание')
    date_of_manufacture = models.DateField(verbose_name='Дата изготовления')
    stock = models.IntegerField(verbose_name='Остаток на складе', default=10)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.product_name or ''


class Order(models.Model):
    order_id = models.CharField(primary_key=True, max_length=36)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    order_date = models.DateField(auto_now=True, verbose_name='Дата заказа')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return str(self.order_id) or ''


class Client(models.Model):
    client_id = models.CharField(primary_key=True, max_length=36)
    client_full_name = models.CharField(max_length=100, verbose_name='ФИО клиента')
    client_email_address = models.EmailField(verbose_name='Адрес электронной почты')
    orders = models.ManyToManyField(Order, verbose_name='Заказы', related_name='clients')

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.client_full_name or ''


class JobTitle(models.Model):
    job_title_id = models.CharField(primary_key=True, max_length=36)
    job_title = models.CharField(max_length=100, verbose_name='Должность')

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'

    def __str__(self):
        return self.job_title or ''


class Delivery(models.Model):
    delivery_id = models.CharField(primary_key=True, max_length=36)
    delivery_service = models.ForeignKey(DeliveryService, on_delete=models.CASCADE, verbose_name='Служба доставки')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты', related_name='deliveries')
    order_date = models.DateField(auto_now=True, verbose_name='Дата доставки')
    delivery_review = models.TextField(verbose_name='Отзыв о доставке')

    class Meta:
        verbose_name = 'Доставка'
        verbose_name_plural = 'Доставки'

    def __str__(self):
        return str(self.delivery_id) or ''


class Employee(models.Model):
    employee_id = models.CharField(primary_key=True, max_length=36)
    employee_full_name = models.CharField(max_length=100, verbose_name='ФИО сотрудника')
    job_title = models.ForeignKey(JobTitle, on_delete=models.CASCADE, verbose_name='Должность')
    employee_address = models.CharField(max_length=100, verbose_name='Адрес')

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def __str__(self):
        return self.employee_full_name or ''


class IncomingProduct(models.Model):
    delivery_number = models.CharField(primary_key=True, max_length=36)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, verbose_name='Поставщик')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name='Сотрудник')
    date = models.DateField(auto_now=True, verbose_name='Дата поставки')

    class Meta:
        verbose_name = 'Поступление товара'
        verbose_name_plural = 'Поступления товара'

    def __str__(self):
        return str(self.delivery_number) or ''


class Application(models.Model):
    application_id = models.CharField(primary_key=True, max_length=36)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    delivery_date = models.DateField(auto_now=True, verbose_name='Дата доставки')

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

    def __str__(self):
        return str(self.application_id) or ''


class Card(models.Model):
    card_id = models.CharField(primary_key=True, max_length=36)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE, verbose_name='Коллекция', related_name='cards')
    product = models.OneToOneField(Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='card')

    class Meta:
        verbose_name = 'Карточка'
        verbose_name_plural = 'Карточки'

    def __str__(self):
        return str(self.card_id) or ''

main_pages/views.py
from django.db import transaction
from django.db.models import Q, F
from django.shortcuts import render, get_object_or_404, redirect
from .models import Collection, Card, Product, Profile
from decimal import Decimal
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages


def base(request):
    return render(request, "base.html")


def main_page(request):
    collections = Collection.objects.all()
    cards = Card.objects.select_related('product__product_color', 'product__product_material').all()
    context = {
        'collections': collections,
        'cards': cards,
        'current_collection': None,
    }
    return render(request, 'main_pages/main_page.html', context)


def search(request):
    query = request.GET.get('query')

    if query:
        products = Product.objects.filter(Q(product_name__icontains=query) | Q(description__icontains=query))
    else:
        products = Product.objects.all()

    collections = Collection.objects.all()

    context = {
        'products': products,
        'active_link': 'main_page',
        'query': query,
        'collections': collections,
    }
    print(f'query = {query}')
    return render(request, 'main_pages/search.html', context)


def collection_view(request, collection_name):
    collection = Collection.objects.get(name=collection_name)
    cards = Card.objects.filter(collection=collection)
    collections = Collection.objects.all()
    context = {
        'collection': collection,
        'cards': cards,
        'collections': collections,
        'current_collection': collection_name,
    }
    return render(request, 'collection.html', context)


def card(request, product_id):
    product = get_object_or_404(Product, product_id=product_id)
    context = {'product': product}
    return render(request, 'main_pages/card.html', context)


def add_to_cart(request):
    product_id = request.POST.get('product_id')
    product = get_object_or_404(Product, product_id=product_id)
    cart1 = request.session.get('cart', {})

    product_data = {
        'id': product.product_id,
        'name': product.product_name,
        'price': round(float(product.product_price), 2),
        'stock': product.stock,
    }

    cart1[product.product_id] = product_data
    request.session['cart'] = cart1

    print(request.session['cart'])

    return redirect('main_pages:cart')


def get_cart(request):
    if 'cart' in request.session:
        cart = request.session['cart']
    else:
        cart = {}

    return cart


def cart(request):
    cart = get_cart(request)
    total_cost = Decimal(0)
    for cart_item in cart.values():
        price = Decimal(cart_item['price'])
        stock = Decimal(cart_item['stock'])
        total_cost += price * stock

    if request.method == 'POST':
        for product_id, cart_item in cart.items():
            quantity_key = f"quantity_{product_id}"
            if quantity_key in request.POST:
                quantity = int(request.POST[quantity_key])
                cart_item['stock'] = quantity

    context = {
        'cart': cart,
        'total_cost': total_cost.quantize(Decimal('0.00')),
    }
    return render(request, 'main_pages/cart.html', context)


def clear_cart(request):
    request.session['cart'] = {}
    return redirect('main_pages:cart')


def update_cart(request):
    if request.method == 'POST':
        cart = request.session.get('cart', {})
        delete_item = request.POST.get('delete_item')
        if delete_item:
            cart.pop(delete_item, None)
        else:
            for key in request.POST:
                if key.startswith('quantity_'):
                    product_id = key.split('quantity_')[1]
                    quantity = int(request.POST[key])
                    cart_item = cart.get(product_id)
                    if cart_item:
                        cart_item['stock'] = quantity
                        if quantity <= 0:
                            del cart[product_id]
        request.session['cart'] = cart

    return redirect('main_pages:cart')


def buy_cart(request):
    if request.method == 'POST':
        cart = get_cart(request)
        with transaction.atomic():
            for product_id, cart_item in cart.items():
                quantity = int(request.POST.get('quantity_' + str(product_id), cart_item['stock']))
                if quantity > 0:
                    product = Product.objects.select_for_update().get(product_id=product_id)
                    if product.stock >= quantity:
                        product.stock -= quantity
                        product.save()

            clear_cart(request)

    return redirect('main_pages:cart')


def delete_cart_item(request, product_id):
    print(f'Deleting product with ID: {product_id}')
    if request.method == 'POST':
        cart = request.session.get('cart', {})
        if product_id in cart:
            del cart[product_id]
            request.session['cart'] = cart
    return redirect('main_pages:cart')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.add_message(request, messages.ERROR, "Неправильный логин или пароль")
            return redirect('/login/')
    else:
        return render(request, 'main_pages/login.html')



def register_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password1')
        FIO = request.POST.get('full_name')
        address = request.POST.get('address')
        image = request.POST.get('picture')
        try:
            user_object = User.objects.create_user(username=username, password=password)
        except Exception as exc:
            return redirect('/signup/')
        profile_object = Profile.objects.create(user=user_object, FIO=FIO, address=address, image=image)
        profile_object.save()
        login(request, user_object)
        return redirect('/')
    else:
        return render(request, 'main_pages/signup.html')


def logout_view(request):
    logout(request)
    print('dddd')
    return redirect('/')

main_pages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %}Hoodie Store{% endblock %}</title>
    <style>
        body.login-page,
        body.signup-page {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .footer {
            background-color: black;
            color: white;
            padding: 20px 0;
        }

        .sticky-footer {
            flex-shrink: 0;
        }

        .nav-left {
            position: sticky;
            top: 100px;
            height: calc(100vh - 100px);
            overflow-y: auto;
        }

        .content-center {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .nav-left ul {
            padding: 0;
        }

        .nav-left li {
            margin-bottom: 10px;
        }

        .nav-left a {
            display: block;
            padding: 10px;
            background-color: #f8f9fa;
            color: #000;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .nav-left a:hover {
            background-color: #e9ecef;
        }

        .nav-left a.active {
            background-color: #007bff;
            color: #fff;
        }

        .nav-left a.active-collection {
            background-color: #ffc107;
            color: #fff;
        }

        .card-hover:hover {
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        transform: scale(1.02);
        transition: box-shadow 0.3s ease, transform 0.3s ease;
        }

        .card .card-image-container {
            height: 200px;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }

        .card .card-image-container img {
            width: 100%;
            height: auto;
            object-fit: cover;
        }
        .form-control {
            flex: 1;
            margin-right: 5px;
        }

        .btn {
            white-space: nowrap;
        }

        .logo-img {
            width: 75px;
            height: auto;
        }

        .input-group {
            display: flex;
            align-items: center;
        }

        @media (max-width: 576px) {
           .logo-img {
               width: 50px;
           }
        }
        .card .card-image-container {
            height: 200px;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }

        .card .card-image-container img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <div class="d-flex flex-column min-vh-100">
        <!-- Header -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main_pages:main_page' %}?active=main_page">
                    <img class="logo-img" src="{% static 'images/logo.png' %}" alt="Logo">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item {% if active_link == 'main_page' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'main_pages:main_page' %}">Новинки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Мужчинам</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Женщинам</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Каталог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">О нас</a>
                        </li>
                    </ul>
                    <a class="navbar-brand" href={% url 'main_pages:cart' %}>
                        <img class="cart-img" src="{% static 'images/cart.svg' %}" alt="Cart">
                    </a>
                    <form class="form-inline" action="{% url 'main_pages:search' %}" method="GET">
                        <div class="input-group">
                            <input class="form-control" type="search" name="query" placeholder="Поиск" aria-label="Search">
                            <button class="btn btn-outline-primary" type="submit">Найти</button>
                        </div>
                    </form>

                    {% if user.is_authenticated %}
                        <div class="dropdown">
                            <a class="navbar-brand dropdown-toggle" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.is_authenticated %}
                                {% if user.profile.picture %}
                                    <img class="logo-img" src="{{ user.profile.picture.url }}" alt="Profile">
                                {% else %}
                                    <img class="logo-img" src="{% static 'images/profile.svg' %}" alt="Profile">
                                {% endif %}
                            {% else %}
                                <img class="logo-img" src="{% static 'images/profile.svg' %}" alt="Profile">
                            {% endif %}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                                <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Профиль</a></li>
                                <li><a class="dropdown-item" href="#">Мои заказы</a></li>
                                <li><a class="dropdown-item" href="/logout/">Выход</a></li>
                            </ul>
                        </div>

                            {% else %}
                                <a class="navbar-brand" href="{% url 'accounts:profile' %}">
                                <img class="logo-img" src="{% static 'images/profile.svg' %}" alt="Profile">
                                </a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <!-- Content -->
        <div class="flex-grow-1">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Footer -->
<footer class="footer sticky-footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <a class="footer-link" href="t.me/COREYSENT">Контакты</a>
            </div>
            <div class="col">
                <a class="footer-link" href="https://vk.com/b0d9bouleg">Социальные сети</a>
            </div>
            <div class="col text-end">
                <p class="text-dark">Все права защищены &copy; 2023</p>
            </div>
        </div>
    </div>
</footer>

    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>
</html>

main_pages/templates/collection.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 order-md-first">
                <div class="nav-left mt-4">
                    <h2>Коллекции</h2>
                    <ul class="list-unstyled">
                        {% for collection in collections %}
                            <li><a class="collection-link {% if collection.name == current_collection %}active-collection{% endif %}" href="{% url 'main_pages:collection_view' collection.name %}">{{ collection.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-8 order-md-last">
                <h2 class="mt-4">Коллекция: {{ collection.name }}</h2>
                <div class="row">
                    {% for card in cards %}
                        <div class="col-md-4">
                            <div class="card mb-4 card-hover">
                                <div class="card-image-container">
                                    <a href="{% url 'main_pages:card' product_id=card.product.product_id %}">
                                        <img src="{{ card.product.product_image.url }}" class="card-img" alt="{{ card.product.product_name }}">
                                    </a>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <p class="text-secondary">{{ card.product.product_name }}</p>
                                        </div>
                                        <div class="col">
                                            <p class="text-secondary">{{ card.product.product_price }}р.</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="badge badge-primary">{{ card.product.discount }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<style>
    .card .card-image-container {
        height: 200px;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
    }

    .card .card-image-container img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
</style>