accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update_profile_submit/', views.update_profile_submit, name='update_profile_submit'),
]

hoodie_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_pages.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255, default='None')
    address = models.CharField(max_length=255, default='None')
    picture = models.ImageField(upload_to='profile_pictures', default='None')

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput,
        error_messages={
            'required': 'Введите пароль',
            'password_mismatch': 'Пароли не совпадают',
            'min_length': 'Пароль должен содержать не менее 8 символов',
            'numeric': 'Пароль не может быть полностью числовым',
            'common_password': 'Пароль не может быть общеупотребляемым',
            'similar_user_info': 'Пароль не может быть слишком похожим на вашу персональную информацию',
        }
    )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['picture', 'full_name', 'address']

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import ProfileForm
from .models import UserProfile
from django.contrib.auth.decorators import login_required


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('main_pages:main_page'))
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            profile = UserProfile(
                user=user,
                full_name=request.POST['full_name'],
                address=request.POST['address'],
                picture=request.FILES['picture']
            )
            profile.save()

            return redirect('accounts:login')

    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')


@login_required(login_url='/login/')
def profile_view(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)
        profile.save()

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect(reverse('accounts:profile'))
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'accounts/profile.html', {'form': form})


def my_orders_view(request):
    return render(request, 'accounts/my_orders.html')


def update_profile(request):
    # Add your logic to handle the profile update here
    return render(request, 'accounts/update_profile.html')


def update_profile_submit(request):
    if request.method == 'POST':
        return redirect('main_pages:profile')
    else:
        return redirect('main_pages:update_profile')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="content-center">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title">Логин</h1>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="id_username">Имя пользователя</label>
                                    {{ form.username }}
                                </div>
                            </div>
                            <br>
                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="id_password">Пароль</label>
                                    {{ form.password }}
                                </div>
                            </div>
                            <br>
                            <div class="form-row">
                                <div class="col">
                                    <button class="btn btn-primary" type="submit">Логин</button>
                                </div>
                            </div>
                        </form>
                        <br>
                        <p>Не зарегистрированы? <a href="{% url 'accounts:signup' %}">Зарегистрироваться</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-center">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2>Профиль</h2>
                    <div class="form-group">
                        <label for="full-name">ФИО</label>
                        <p>{{ request.user.profile.FIO }}</p>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="address">Адрес</label>
                        <p>{{ request.user.profile.address }}</p>
                    </div>
                    <br>
                    {% if request.user.profile.image %}
                        <div class="form-group">
                            <label for="profile-picture">Фото профиля</label>
                            <br>
                            <img src="{{ request.user.profile.image.url }}" alt="Profile Picture" class="img-fluid">
                        </div>
                    {% else %}
                        <p>Фото профиля отсутствует.</p>
                    {% endif %}
                    <br>
                    <a href="{% url 'accounts:update_profile' %}" class="btn btn-primary">Обновить профиль</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const passwordInput = document.getElementById('id_password1');
        const confirmPasswordInput = document.getElementById('id_password2');
        const passwordError = document.getElementById('password-error');
        const confirmPasswordError = document.getElementById('confirm-password-error');
        const passwordPattern = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;

        passwordInput.addEventListener('input', function() {
            const password = passwordInput.value;
            const isValid = passwordPattern.test(password);

            if (!isValid) {
                passwordError.textContent = 'Пароль должен содержать не менее 8 символов и не может быть полностью числовым.';
                passwordError.style.color = 'red';
            } else {
                passwordError.textContent = '';
            }
        });

        confirmPasswordInput.addEventListener('input', function() {
            const password = passwordInput.value;
            const confirmPassword = confirmPasswordInput.value;

            if (password !== confirmPassword) {
                confirmPasswordError.textContent = 'Пароли не совпадают.';
                confirmPasswordError.style.color = 'red';
            } else {
                confirmPasswordError.textContent = '';
            }
        });

        window.addEventListener('beforeunload', function(event) {
            passwordError.textContent = '';
            confirmPasswordError.textContent = '';
        });
    });
</script>

<div class="content-center">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Регистрация</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <br>
                    <div class="form-group">
                        {{ form.password1.label_tag }}
                        {{ form.password1 }}
                    </div>
                    <br>
                    <div class="form-group">
                        {{ form.password2.label_tag }}
                        {{ form.password2 }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_full_name">ФИО:</label>
                        <input type="text" name="full_name" id="id_full_name">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_address">Адрес:</label>
                        <input type="text" name="address" id="id_address">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_picture">Фото профиля:</label>
                        <input type="file" name="picture" id="id_picture">
                    </div>
                    <br>
                    <div id="password-error"></div>
                    <br>
                    <div id="confirm-password-error"></div>
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </form>
                <br>
                <p>Уже есть аккаунт? <a href="{% url 'accounts:login' %}">Войти</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}